#pragma once

#define FLASH_SIZE ((*(volatile uint16_t *) 0x1FFFF7E0) * 1024)

#define FIRMWARE_SLOT_SIZE    (48 * 1024) // 48KB
#define FIRMWARE_SLOT_1_START (BOOTLOADER_START + BOOTLOADER_SIZE)
#define FIRMWARE_SLOT_2_START (FIRMWARE_SLOT_1_START + FIRMWARE_SLOT_SIZE)
